name: Auto Changelog

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          git config user.name "CI Bot"
          git config user.email "ci@neuxdotdev.my.id"

      - run: |
          git fetch --all
          git reset --hard origin/master
          git log --pretty=format:"%h %ad %s" --date=short > changelog

      - run: |
          git add changelog
          git commit -m "Update changelog [$(date +'%Y-%m-%d %H:%M:%S')]" || echo "No changes to commit"
          git push origin master --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}